# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(855, 360)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 331))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.save_node_button = QtWidgets.QPushButton(self.tab)
        self.save_node_button.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.save_node_button.setObjectName("save_node_button")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 101, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 89, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.node_x = QtWidgets.QLineEdit(self.layoutWidget)
        self.node_x.setObjectName("node_x")
        self.horizontalLayout.addWidget(self.node_x)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 88, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.node_y = QtWidgets.QLineEdit(self.layoutWidget1)
        self.node_y.setObjectName("node_y")
        self.horizontalLayout_2.addWidget(self.node_y)
        self.remove_node_button = QtWidgets.QPushButton(self.tab)
        self.remove_node_button.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.remove_node_button.setObjectName("remove_node_button")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(120, 10, 231, 281))
        self.groupBox_6.setObjectName("groupBox_6")
        self.node_list = QtWidgets.QListWidget(self.groupBox_6)
        self.node_list.setGeometry(QtCore.QRect(10, 20, 211, 251))
        self.node_list.setObjectName("node_list")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 101, 161))
        self.groupBox.setObjectName("groupBox")
        self.elem_name = QtWidgets.QLineEdit(self.groupBox)
        self.elem_name.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.elem_name.setObjectName("elem_name")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 50, 81, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.elem_width = QtWidgets.QLineEdit(self.layoutWidget2)
        self.elem_width.setObjectName("elem_width")
        self.verticalLayout.addWidget(self.elem_width)
        self.elem_height = QtWidgets.QLineEdit(self.layoutWidget2)
        self.elem_height.setObjectName("elem_height")
        self.verticalLayout.addWidget(self.elem_height)
        self.elem_elasticity = QtWidgets.QLineEdit(self.layoutWidget2)
        self.elem_elasticity.setObjectName("elem_elasticity")
        self.verticalLayout.addWidget(self.elem_elasticity)
        self.elem_inertia_coeff = QtWidgets.QLineEdit(self.layoutWidget2)
        self.elem_inertia_coeff.setObjectName("elem_inertia_coeff")
        self.verticalLayout.addWidget(self.elem_inertia_coeff)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(120, 10, 231, 271))
        self.groupBox_7.setObjectName("groupBox_7")
        self.element_list = QtWidgets.QListWidget(self.groupBox_7)
        self.element_list.setGeometry(QtCore.QRect(10, 20, 211, 241))
        self.element_list.setObjectName("element_list")
        self.save_element_button = QtWidgets.QPushButton(self.tab_2)
        self.save_element_button.setGeometry(QtCore.QRect(10, 180, 101, 28))
        self.save_element_button.setObjectName("save_element_button")
        self.remove_element_button = QtWidgets.QPushButton(self.tab_2)
        self.remove_element_button.setGeometry(QtCore.QRect(10, 220, 101, 28))
        self.remove_element_button.setObjectName("remove_element_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 161, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.section_list_box = QtWidgets.QComboBox(self.groupBox_8)
        self.section_list_box.setGeometry(QtCore.QRect(10, 20, 141, 22))
        self.section_list_box.setObjectName("section_list_box")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 161, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 144, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.left_side_node = QtWidgets.QComboBox(self.layoutWidget_2)
        self.left_side_node.setObjectName("left_side_node")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.left_side_node)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.right_side_node = QtWidgets.QComboBox(self.layoutWidget_2)
        self.right_side_node.setObjectName("right_side_node")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.right_side_node)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.assign_element_button = QtWidgets.QPushButton(self.tab_10)
        self.assign_element_button.setGeometry(QtCore.QRect(20, 150, 151, 31))
        self.assign_element_button.setObjectName("assign_element_button")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 116, 81))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pinned_label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.pinned_label_2.setStyleSheet("")
        self.pinned_label_2.setText("")
        self.pinned_label_2.setObjectName("pinned_label_2")
        self.verticalLayout_5.addWidget(self.pinned_label_2)
        self.pinned_check_2 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.pinned_check_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pinned_check_2.setObjectName("pinned_check_2")
        self.verticalLayout_5.addWidget(self.pinned_check_2)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 100, 116, 81))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.roller_label_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.roller_label_2.setStyleSheet("")
        self.roller_label_2.setText("")
        self.roller_label_2.setObjectName("roller_label_2")
        self.verticalLayout_6.addWidget(self.roller_label_2)
        self.roller_check_2 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.roller_check_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.roller_check_2.setObjectName("roller_check_2")
        self.verticalLayout_6.addWidget(self.roller_check_2)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 190, 116, 81))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fixed_label_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.fixed_label_2.setStyleSheet("")
        self.fixed_label_2.setText("")
        self.fixed_label_2.setObjectName("fixed_label_2")
        self.verticalLayout_7.addWidget(self.fixed_label_2)
        self.fixed_check_2 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.fixed_check_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.fixed_check_2.setObjectName("fixed_check_2")
        self.verticalLayout_7.addWidget(self.fixed_check_2)
        self.support_node_box = QtWidgets.QComboBox(self.tab_5)
        self.support_node_box.setGeometry(QtCore.QRect(140, 200, 73, 22))
        self.support_node_box.setObjectName("support_node_box")
        self.save_support_button = QtWidgets.QPushButton(self.tab_5)
        self.save_support_button.setGeometry(QtCore.QRect(140, 230, 73, 28))
        self.save_support_button.setObjectName("save_support_button")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 211, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.add_point_load_button = QtWidgets.QPushButton(self.groupBox_3)
        self.add_point_load_button.setGeometry(QtCore.QRect(110, 140, 93, 28))
        self.add_point_load_button.setObjectName("add_point_load_button")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 141, 111))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget_7)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.node_box = QtWidgets.QComboBox(self.layoutWidget_7)
        self.node_box.setObjectName("node_box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.node_box)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.x_magnitude = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.x_magnitude.setObjectName("x_magnitude")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.x_magnitude)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.y_magnitude = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.y_magnitude.setObjectName("y_magnitude")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.y_magnitude)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.moment_magnitude = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.moment_magnitude.setObjectName("moment_magnitude")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.moment_magnitude)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 190, 211, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 30, 81, 53))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.member_box = QtWidgets.QComboBox(self.layoutWidget_8)
        self.member_box.setObjectName("member_box")
        self.verticalLayout_8.addWidget(self.member_box)
        self.distributed_load = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.distributed_load.setObjectName("distributed_load")
        self.verticalLayout_8.addWidget(self.distributed_load)
        self.add_distributed_load_button = QtWidgets.QPushButton(self.groupBox_4)
        self.add_distributed_load_button.setGeometry(QtCore.QRect(110, 80, 93, 28))
        self.add_distributed_load_button.setObjectName("add_distributed_load_button")
        self.analysis_button = QtWidgets.QPushButton(self.tab_6)
        self.analysis_button.setGeometry(QtCore.QRect(240, 270, 101, 31))
        self.analysis_button.setObjectName("analysis_button")
        self.tabWidget.addTab(self.tab_6, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(400, 10, 441, 331))
        self.tabWidget_2.setMouseTracking(True)
        self.tabWidget_2.setTabletTracking(True)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.display_label_node = QtWidgets.QLabel(self.tab_7)
        self.display_label_node.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.display_label_node.setText("")
        self.display_label_node.setObjectName("display_label_node")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.display_label = QtWidgets.QLabel(self.tab_3)
        self.display_label.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.display_label.setText("")
        self.display_label.setObjectName("display_label")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.displacement_label = QtWidgets.QLabel(self.tab_4)
        self.displacement_label.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.displacement_label.setText("")
        self.displacement_label.setObjectName("displacement_label")
        self.tabWidget_2.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "2B Çerçeve Analiz Programı"))
        self.save_node_button.setText(_translate("Form", "Save Node"))
        self.groupBox_5.setTitle(_translate("Form", "Coordinates"))
        self.label.setText(_translate("Form", "X :"))
        self.label_2.setText(_translate("Form", "Y :"))
        self.remove_node_button.setText(_translate("Form", "Remove Node"))
        self.groupBox_6.setTitle(_translate("Form", "Node List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Nodes"))
        self.groupBox.setTitle(_translate("Form", "Section Prop."))
        self.elem_name.setPlaceholderText(_translate("Form", "Section Name"))
        self.elem_width.setPlaceholderText(_translate("Form", "Width"))
        self.elem_height.setPlaceholderText(_translate("Form", "Height"))
        self.elem_elasticity.setPlaceholderText(_translate("Form", "Elasticity"))
        self.elem_inertia_coeff.setPlaceholderText(_translate("Form", "Inertia Coeff"))
        self.groupBox_7.setTitle(_translate("Form", "Element List"))
        self.save_element_button.setText(_translate("Form", "Save"))
        self.remove_element_button.setText(_translate("Form", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sections"))
        self.groupBox_8.setTitle(_translate("Form", "Element Section"))
        self.groupBox_2.setTitle(_translate("Form", "Element Nodes"))
        self.label_3.setText(_translate("Form", "Left Node"))
        self.label_4.setText(_translate("Form", "Right Node"))
        self.assign_element_button.setText(_translate("Form", "Assign"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Form", "Elements"))
        self.pinned_check_2.setText(_translate("Form", "Pinned Support"))
        self.roller_check_2.setText(_translate("Form", "Roller Support"))
        self.fixed_check_2.setText(_translate("Form", "Fixed Support"))
        self.save_support_button.setText(_translate("Form", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Supports"))
        self.groupBox_3.setTitle(_translate("Form", "Point Loads"))
        self.add_point_load_button.setText(_translate("Form", "Ekle"))
        self.label_5.setText(_translate("Form", "Node"))
        self.label_6.setText(_translate("Form", "X Dir"))
        self.x_magnitude.setPlaceholderText(_translate("Form", "X Magnitude"))
        self.label_7.setText(_translate("Form", "Y Dir"))
        self.y_magnitude.setPlaceholderText(_translate("Form", "Y Magnitude"))
        self.label_8.setText(_translate("Form", "Moment"))
        self.moment_magnitude.setPlaceholderText(_translate("Form", "Moment"))
        self.groupBox_4.setTitle(_translate("Form", "Distributed Loads"))
        self.distributed_load.setPlaceholderText(_translate("Form", "Magnitude"))
        self.add_distributed_load_button.setText(_translate("Form", "Ekle"))
        self.analysis_button.setText(_translate("Form", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Loads"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "Nodes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "Elements"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Displacements"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

